# compose.yaml
services:
  grafana:
    image: grafana/grafana-oss
#    container_name: grafana
    entrypoint: ['/bin/sh', '-c' , '. /tmp/bin/set-env.sh; /run.sh']
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
    secrets:
      - influxdb2-admin-token
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      - ./bin/:/tmp/bin
    networks:
      - infra

  influxdb:
    image: influxdb:2
#    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: stocks
      DOCKER_INFLUXDB_INIT_BUCKET: stocks
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data-stocks
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config-stocks
        target: /etc/influxdb2
    networks:
      - infra

  postgres:
    image: postgres:16.4
#    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/dbs-init.sql:/docker-entrypoint-initdb.d/dbs-init-config.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=stocks_config

secrets:
  influxdb2-admin-username:
    file: .env.influxdb2-admin-username
  influxdb2-admin-password:
    file: .env.influxdb2-admin-password
  influxdb2-admin-token:
    file: .env.influxdb2-admin-token
volumes:
  influxdb2-data-stocks:
  influxdb2-config-stocks:

networks:
  infra:
    name: infra-stocks
