apiVersion: 1
datasources:
  - name: InfluxDB
    version: 2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      defaultBucket: stocks
      httpMode: POST
      organization: stocks
      version: Flux
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
#  - name: Prometheus
#    type: prometheus
#    url: http://prometheus:9090
#    isDefault: true
#    access: proxy
#    editable: true